version: '2.4'

services:
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    ports:
      - 8080

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - app
